server:
  port: 5000

spring:
  application:
    name: grocery_list_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dblistmangementsaidboudad-3.cnuro8frglgi.eu-west-2.rds.amazonaws.com:5432/grocery_list_service
    username: saidboudad
    password: ******
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ***
    password: ***

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
