server:
  port: 8888

spring:
  application:
    name: grocery_list_service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/grocery_list_service
    username: postgres
    password: Saidboudad+
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect